service: project-service

custom:
  projectsBucket: dev-scholance-projects

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    MONGO_URI: ${file(./serverless.env.yml):dev.MONGO_URI}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

functions:
  listProjects:
    handler: handler.listProjects
    events:
      - http:
          path: projects
          method: get
          cors: true

  createProject:
    handler: handler.createProject
    events:
      - http:
          path: projects
          method: post
          cors: true

  getProject:
    handler: handler.getProject
    events:
      - http:
          path: projects/{project_id}
          method: get
          cors: true

  updateProject:
    handler: handler.updateProject
    events:
      - http:
          path: projects/{project_id}
          method: put
          cors: true

  deleteProject:
    handler: handler.deleteProject
    events:
      - http:
          path: projects/{project_id}
          method: delete
          cors: true

  projectSignup:
    handler: handler.projectSignup
    events:
      - http:
          path: projects/{project_id}/entries
          method: post
          cors: true

  projectSignoff:
    handler: handler.projectSignoff
    events:
      - http:
          path: projects/{project_id}/entries
          method: delete
          cors: true

  createSupplementalResourceFile:
    handler: handler.createSupplementalResourceFile
    events:
      - http:
          path: projects/{project_id}/supplemental-resources/file
          method: post
          cors: true

  createEntryAsset:
    handler: handler.createEntryAsset
    events:
      - http:
          path: projects/{project_id}/entries/{user_id}/assets
          method: post
          cors: true

  createEntryAssetFile:
    handler: handler.createEntryAssetFile
    events:
      - http:
          path: projects/{project_id}/entries/{user_id}/assets/file
          method: post
          cors: true
