service: project-service

custom:
  projectsBucket: dev-scholance-projects

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, 'dev'}
  environment:
    MONGO_URI: ${file(./serverless.env.yml):${self:provider.stage}.MONGO_URI}
    AUTH_URI: ${file(./serverless.env.yml):${self:provider.stage}.AUTH_URI}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

package:
  exclude:
    - test/**
    - .git/**
    - docs/**

functions:

  #########
  # PROJECT
  #########

  listProjects:
    handler: controllers/project.listProjects
    events:
      - http:
          path: projects
          method: get
          cors: true

  createProject:
    handler: controllers/project.createProject
    events:
      - http:
          path: projects
          method: post
          cors: true
          authorizer:
            arn: ${file(./serverless.env.yml):${self:provider.stage}.AUTH_URI}
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            identityValidationExpression: ^Bearer [-0-9a-zA-z\.]*$

  getProject:
    handler: controllers/project.getProject
    events:
      - http:
          path: projects/{project_id}
          method: get
          cors: true

  updateProject:
    handler: controllers/project.updateProject
    events:
      - http:
          path: projects/{project_id}
          method: put
          cors: true
          authorizer:
            arn: ${file(./serverless.env.yml):${self:provider.stage}.AUTH_URI}
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            identityValidationExpression: ^Bearer [-0-9a-zA-z\.]*$

  deleteProject:
    handler: controllers/project.deleteProject
    events:
      - http:
          path: projects/{project_id}
          method: delete
          cors: true
          authorizer:
            arn: ${file(./serverless.env.yml):${self:provider.stage}.AUTH_URI}
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            identityValidationExpression: ^Bearer [-0-9a-zA-z\.]*$

  updateProjectStatus:
    handler: controllers/project.updateProjectStatus
    events:
      - http:
          path: projects/{project_id}/status
          method: put
          cors: true
          authorizer:
            arn: ${file(./serverless.env.yml):${self:provider.stage}.AUTH_URI}
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            identityValidationExpression: ^Bearer [-0-9a-zA-z\.]*$

  createProjectComment:
    handler: controllers/project.createProjectComment
    events:
      - http:
          path: projects/{project_id}/comments
          method: post
          cors: true
          authorizer:
            arn: ${file(./serverless.env.yml):${self:provider.stage}.AUTH_URI}
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            identityValidationExpression: ^Bearer [-0-9a-zA-z\.]*$

  deleteProjectComment:
    handler: controllers/project.deleteProjectComment
    events:
      - http:
          path: projects/{project_id}/comments/{comment_id}
          method: delete
          cors: true
          authorizer:
            arn: ${file(./serverless.env.yml):${self:provider.stage}.AUTH_URI}
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            identityValidationExpression: ^Bearer [-0-9a-zA-z\.]*$

  ########################
  # SUPPLEMENTAL RESOURCES
  ########################

  createSupplementalResource:
    handler: controllers/project.createSupplementalResource
    events:
      - http:
          path: projects/{project_id}/supplemental-resources
          method: post
          cors: true
          authorizer:
            arn: ${file(./serverless.env.yml):${self:provider.stage}.AUTH_URI}
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            identityValidationExpression: ^Bearer [-0-9a-zA-z\.]*$

  createSupplementalResourceFile:
    handler: controllers/project.createSupplementalResourceFile
    events:
      - http:
          path: projects/{project_id}/supplemental-resources/file
          method: post
          cors: true
          authorizer:
            arn: ${file(./serverless.env.yml):${self:provider.stage}.AUTH_URI}
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            identityValidationExpression: ^Bearer [-0-9a-zA-z\.]*$

  deleteSupplementalResource:
    handler: controllers/project.deleteSupplementalResource
    events:
      - http:
          path: projects/{project_id}/supplemental-resources/{asset_id}
          method: delete
          cors: true
          authorizer:
            arn: ${file(./serverless.env.yml):${self:provider.stage}.AUTH_URI}
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            identityValidationExpression: ^Bearer [-0-9a-zA-z\.]*$

  ######################
  # ENTRY & ENTRY ASSETS
  ######################

  projectSignup:
    handler: controllers/project.projectSignup
    events:
      - http:
          path: projects/{project_id}/entries
          method: post
          cors: true
          authorizer:
            arn: ${file(./serverless.env.yml):${self:provider.stage}.AUTH_URI}
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            identityValidationExpression: ^Bearer [-0-9a-zA-z\.]*$

  projectSignoff:
    handler: controllers/project.projectSignoff
    events:
      - http:
          path: projects/{project_id}/entries/{user_id}
          method: delete
          cors: true
          authorizer:
            arn: ${file(./serverless.env.yml):${self:provider.stage}.AUTH_URI}
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            identityValidationExpression: ^Bearer [-0-9a-zA-z\.]*$

  getEntry:
    handler: controllers/project.getEntryByStudentId
    events:
      - http:
          path: projects/{project_id}/entries/{user_id}
          method: get
          cors: true
          authorizer:
            arn: ${file(./serverless.env.yml):${self:provider.stage}.AUTH_URI}
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            identityValidationExpression: ^Bearer [-0-9a-zA-z\.]*$

  updateEntry:
    handler: controllers/project.updateEntry
    events:
      - http:
          path: projects/{project_id}/entries/{user_id}
          method: put
          cors: true
          authorizer:
            arn: ${file(./serverless.env.yml):${self:provider.stage}.AUTH_URI}
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            identityValidationExpression: ^Bearer [-0-9a-zA-z\.]*$

  createEntryAsset:
    handler: controllers/project.createEntryAsset
    events:
      - http:
          path: projects/{project_id}/entries/{user_id}/assets
          method: post
          cors: true
          authorizer:
            arn: ${file(./serverless.env.yml):${self:provider.stage}.AUTH_URI}
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            identityValidationExpression: ^Bearer [-0-9a-zA-z\.]*$

  createEntryAssetFile:
    handler: controllers/project.createEntryAssetFile
    events:
      - http:
          path: projects/{project_id}/entries/{user_id}/assets/file
          method: post
          cors: true
          authorizer:
            arn: ${file(./serverless.env.yml):${self:provider.stage}.AUTH_URI}
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            identityValidationExpression: ^Bearer [-0-9a-zA-z\.]*$

  deleteEntryAsset:
    handler: controllers/project.deleteEntryAsset
    events:
      - http:
          path: projects/{project_id}/entries/{user_id}/assets/{asset_id}
          method: delete
          cors: true
          authorizer:
            arn: ${file(./serverless.env.yml):${self:provider.stage}.AUTH_URI}
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            identityValidationExpression: ^Bearer [-0-9a-zA-z\.]*$
  createEntryComment:
    handler: controllers/project.createEntryComment
    events:
      - http:
          path: projects/{project_id}/entries/{user_id}/comments
          method: post
          cors: true
          authorizer:
            arn: ${file(./serverless.env.yml):${self:provider.stage}.AUTH_URI}
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            identityValidationExpression: ^Bearer [-0-9a-zA-z\.]*$

  deleteEntryComment:
    handler: controllers/project.deleteEntryComment
    events:
      - http:
          path: projects/{project_id}/entries/{user_id}/comments/{comment_id}
          method: delete
          cors: true
          authorizer:
            arn: ${file(./serverless.env.yml):${self:provider.stage}.AUTH_URI}
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            identityValidationExpression: ^Bearer [-0-9a-zA-z\.]*$