service: project-service

custom:
  projectsBucket: dev-scholance-projects

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    MONGO_URI: ${file(./serverless.env.yml):dev.MONGO_URI}
    AUTH_URI: ${file(./serverless.env.yml):dev.AUTH_URI}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

functions:
  listProjects:
    handler: handler.listProjects
    events:
      - http:
          path: projects
          method: get
          cors: true

  createProject:
    handler: handler.createProject
    events:
      - http:
          path: projects
          method: post
          cors: true
          authorizer:
            arn: ${file(./serverless.env.yml):dev.AUTH_URI}
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            identityValidationExpression: ^Bearer [-0-9a-zA-z\.]*$

  getProject:
    handler: handler.getProject
    events:
      - http:
          path: projects/{project_id}
          method: get
          cors: true

  updateProject:
    handler: handler.updateProject
    events:
      - http:
          path: projects/{project_id}
          method: put
          cors: true
          authorizer:
            arn: ${file(./serverless.env.yml):dev.AUTH_URI}
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            identityValidationExpression: ^Bearer [-0-9a-zA-z\.]*$

  deleteProject:
    handler: handler.deleteProject
    events:
      - http:
          path: projects/{project_id}
          method: delete
          cors: true
          authorizer:
            arn: ${file(./serverless.env.yml):dev.AUTH_URI}
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            identityValidationExpression: ^Bearer [-0-9a-zA-z\.]*$

  projectSignup:
    handler: handler.projectSignup
    events:
      - http:
          path: projects/{project_id}/entries
          method: post
          cors: true
          authorizer:
            arn: ${file(./serverless.env.yml):dev.AUTH_URI}
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            identityValidationExpression: ^Bearer [-0-9a-zA-z\.]*$

  projectSignoff:
    handler: handler.projectSignoff
    events:
      - http:
          path: projects/{project_id}/entries/{user_id}
          method: delete
          cors: true
          authorizer:
            arn: ${file(./serverless.env.yml):dev.AUTH_URI}
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            identityValidationExpression: ^Bearer [-0-9a-zA-z\.]*$

  createSupplementalResourceFile:
    handler: handler.createSupplementalResourceFile
    events:
      - http:
          path: projects/{project_id}/supplemental-resources/file
          method: post
          cors: true
          authorizer:
            arn: ${file(./serverless.env.yml):dev.AUTH_URI}
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            identityValidationExpression: ^Bearer [-0-9a-zA-z\.]*$

  deleteSupplementalResource:
    handler: handler.deleteSupplementalResource
    events:
      - http:
          path: projects/{project_id}/supplemental-resources/{asset_id}
          method: delete
          cors: true
          authorizer:
            arn: ${file(./serverless.env.yml):dev.AUTH_URI}
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            identityValidationExpression: ^Bearer [-0-9a-zA-z\.]*$

  getEntry:
    handler: handler.getEntry
    events:
      - http:
          path: projects/{project_id}/entries/{user_id}
          method: get
          cors: true
          authorizer:
            arn: ${file(./serverless.env.yml):dev.AUTH_URI}
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            identityValidationExpression: ^Bearer [-0-9a-zA-z\.]*$

  createEntryAsset:
    handler: handler.createEntryAsset
    events:
      - http:
          path: projects/{project_id}/entries/{user_id}/assets
          method: post
          cors: true
          authorizer:
            arn: ${file(./serverless.env.yml):dev.AUTH_URI}
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            identityValidationExpression: ^Bearer [-0-9a-zA-z\.]*$

  createEntryAssetFile:
    handler: handler.createEntryAssetFile
    events:
      - http:
          path: projects/{project_id}/entries/{user_id}/assets/file
          method: post
          cors: true
          authorizer:
            arn: ${file(./serverless.env.yml):dev.AUTH_URI}
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            identityValidationExpression: ^Bearer [-0-9a-zA-z\.]*$

  deleteEntryAsset:
    handler: handler.deleteEntryAsset
    events:
      - http:
          path: projects/{project_id}/entries/{user_id}/assets/{asset_id}
          method: delete
          cors: true
          authorizer:
            arn: ${file(./serverless.env.yml):dev.AUTH_URI}
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            identityValidationExpression: ^Bearer [-0-9a-zA-z\.]*$
